logging:
  config: classpath:logback.xml
server:
  port: 8081
  session-timeout: 60
mybatis:
     mapperLocations: classpath:mybatis/*/*.xml
     typeAliasesPackage: com.testext.springboot.dao
     mapperScanPackage: com.testext.springboot.dao
     configLocation: classpath:mybatis-config.xml

mysql:
    datasource:
        readSize: 2  #读库个数
        type: com.alibaba.druid.pool.DruidDataSource
        mapperLocations: classpath*:com/testext/springboot/dao/*.xml
        configLocation: classpath*:mybatis-config.xml
        write:
           url: jdbc:mysql://127.0.0.1:3306/testext?useUnicode=true&amp;characterEncoding=utf-8
           username: root
           password: password
           driver-class-name: com.mysql.jdbc.Driver
           minIdle: 5
           maxActive: 100
           initialSize: 10
           maxWait: 60000
           timeBetweenEvictionRunsMillis: 60000
           minEvictableIdleTimeMillis: 300000
           validationQuery: select 'x'
           testWhileIdle: true
           testOnBorrow: false
           testOnReturn: false
           poolPreparedStatements: true
           maxPoolPreparedStatementPerConnectionSize: 50
           removeAbandoned: true
           filters: stat
        read01:
           url: jdbc:mysql://127.0.0.1:3307/testext?useUnicode=true&amp;characterEncoding=utf-8
           username: root
           password: password
           driver-class-name: com.mysql.jdbc.Driver
           minIdle: 5
           maxActive: 100
           initialSize: 10
           maxWait: 60000
           timeBetweenEvictionRunsMillis: 60000
           minEvictableIdleTimeMillis: 300000
           validationQuery: select 'x'
           testWhileIdle: true
           testOnBorrow: false
           testOnReturn: false
           poolPreparedStatements: true
           maxPoolPreparedStatementPerConnectionSize: 50
           removeAbandoned: true
           filters: stat
        read02:
           url: jdbc:mysql://127.0.0.1:3308/testext?useUnicode=true&amp;characterEncoding=utf-8
           username: root
           password: password
           driver-class-name: com.mysql.jdbc.Driver
           minIdle: 5
           maxActive: 100
           initialSize: 10
           maxWait: 60000
           timeBetweenEvictionRunsMillis: 60000
           minEvictableIdleTimeMillis: 300000
           validationQuery: select 'x'
           testWhileIdle: true
           testOnBorrow: false
           testOnReturn: false
           poolPreparedStatements: true
           maxPoolPreparedStatementPerConnectionSize: 50
           removeAbandoned: true
           filters: stat
spring:
  activemq:
  #<value>failover:(tcp://192.168.10.188:61616,tcp://192.168.10.189:61616)</value>
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin